### ISSUE TITLE
Encontro FrontendBR - BrazilJS POA

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/forum#675]
Ae galera, meio em cima da hora, mas bora fazer um encontro FrontendBR?

22h?

Lugar de sempre https://g.co/kgs/GTg3oA

**Comment by kivervinicius** [comment]
putz, tivesse avisado antes tinha programado para chegar hoje, rs, boa galera até amanhã então no evento!

**Comment by eduardojmatos** [comment]
@kivervinicius foi mal mano, falha minha não ter criado antes :(

Mas sexta pode rolar outros rolês :)

**Comment by alinebastos** [comment]
Opa, vamos @willianjusten @woliveiras e Adeonir (que eu não consigo marcar, haha)?

**Comment by guiseek** [comment]
Por mim, já é... Qual horário?!

Em 24 de ago de 2017 11:35 AM, "Aline Bastos" <notifications@github.com>
escreveu:

**Comment by kivervinicius** [comment]
Hoje chego ai as 00h, amanhã é nós

**Comment by eduardojmatos** [comment]
@guiseek 22h!

**Comment by phenriqueleao** [comment]
Infelizmente não vou por motivos de formatura de amigo quase irmão. Ano que vem pretendo estar dentro!

**Comment by guiseek** [comment]
Começar as 22h? Oloco, pq tão tarde? Bora pra lá umas 19, 20h pô...

Em 24 de ago de 2017 3:43 PM, "Pedro Henrique Leão" <
notifications@github.com> escreveu:

Infelizmente não vou por motivos de formatura de amigo quase irmão. Ano que
vem pretendo estar dentro!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/frontendbr/forum/issues/675#issuecomment-324722044>,
or mute
the thread

**Comment by eduardojmatos** [comment]
@guiseek pode ser mano! É que alguns vão chegar durante a noite de vôos. Eu sou um deles heheh

Mas quem quiser colar cedo, é tranquilo! =D

**Comment by matheusml** [comment]
Fecho algum pra sexta/sábado. Hoje vou chegar lá de madrugada só :(

**Comment by kivervinicius** [comment]
Sexta ou sábado fechou

**Comment by LFeh** [comment]
Não fui, mas bom encontro pra todos e mandem um beijo pra mim de lá :)

**Comment by adrianojdesouza** [comment]
Massa hein, eu topo acho que chego antes das 22

**Comment by eduardojmatos** [comment]
@adrianojdesouza É nois!

**Comment by guiseek** [comment]
Eu e o @gustavocostaw estamos no Casa Azul tomando umas e umas 21h vamos
pra lá!

Em 24 de ago de 2017 7:50 PM, "Eduardo Matos" <notifications@github.com>
escreveu:

**Comment by ricardomaleixo** [comment]
@gustavoquinalha

**Comment by guiseek** [comment]
Cola aqui no hostel ricardooioooo

Em 24 de ago de 2017 8:07 PM, "Ricardo Martins Aleixo" <
notifications@github.com> escreveu:

@gustavoquinalha <https://github.com/gustavoquinalha>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/frontendbr/forum/issues/675#issuecomment-324781304>,
or mute
the thread

**Comment by adrianojdesouza** [comment]
E aii galera to aqui

**Comment by eduardojmatos** [comment]
@adrianojdesouza Tô chegando no hotel e já vou pra aí

**Comment by yanmagale** [comment]
Sim, estamos aqui :D

**Comment by gefymarcos** [comment]
Tô chegando por aí também

**Comment by eduardojmatos** [comment]
![img_9696](https://user-images.githubusercontent.com/1279783/29701304-4d095852-8941-11e7-9dfa-412fae208150.JPG)

**Comment by GustavoCostaW** [comment]
\o/

**Comment by glauberramos** [comment]
vai rolar outro?

**Comment by oliveriojnn** [comment]
Muito bom. Tava pensando em ir pra o de Fortaleza, que é mais próximo!

Valeu a pena, galera? :D

**Comment by woliveiras** [comment]
Perdi o rolê... No próximo eu vou um dia antes só pra encontrar todo mundo!!

Minha única tristeza no evento foi essa: não conseguir encontrar todo mundo pra um café. :cry:

**Comment by bernardocs** [comment]
Agora que vi essa thread!! D:

**Comment by adrianojdesouza** [comment]
@oliveriojnn não pense, vá. hauhauhaua e mais ainda, se der chegue um dia antes e vá beber com a galera.

**Comment by eduardojmatos** [comment]
Muito bom galera! A ideia é quem for em Fortaleza organizar um também. Se souberem de alguém que vá e queira organizar, pode criar outra issue =D

Vou fechar isso pra gente não poluir nossa lista.
